BOT_TOKEN: str = 'MTA4MjU3MDI5MDc3ODg3Nzk3Mw.G52P9i.YXyHtSM8TxcgJrCm_gXgi1CAHsik-MaBqMlIUk'

BOT_PREFIX = '$'
BOT_NAME = ''

STARTUP_MESSAGE = 'Starting bot...'
STARTUP_COMPLETE_MESSAGE = 'Startup Complete'